apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: feedrs
            imagePullPolicy: IfNotPresent
            name: cronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
